export const AdditionError = new Error('Can not add')
export const SubstractionError = new Error('Can not substract')
export const MultiplicationError = new Error('Can not multiply by zero')
export const DivisionError = new Error('Can not divide by zero')
export const ModulusError = new Error('Can not take modulus of zero')