name: Run Aspell

on:
  push:
    branches: ["master"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: spellcheck readme
        uses: reitermarkus/aspell@v1.0.0
        with:
          files: README.md
          args: --lang=en_GB --mode=markdown
